name = "miss-chaos-backend"
main = "dist/index.js"
compatibility_date = "2026-01-18"
type = "modules"

[build]
command = "npm run build"
upload_format = "service-worker"

[[kv_namespaces]]
binding = "MEMORY"
id = "2eb4c3875662467b8f89d537bcd74535"
